### ISSUE TITLE
Tvorba hesla nepodporuje speciální znaky.

### ISSUE THREAD

**Issue by Askaru** [TekuSP/WorldOfStories#2]
Při registraci v kolonkách "zadejte heslo" nejsou podporovány speciální znaky. 
Ozkoušeno pouze na "."
Jinak rozpoznávání velkých, malých písmen a číslic funguje, jak má.

**Comment by TekuSP** [comment]
Regex pro kontrolu hesla pozměnen. Patch 0.03 A.
