### ISSUE TITLE
Spouštění chybí ikonka na liště

### ISSUE THREAD

**Issue by Askaru** [TekuSP/WorldOfStories#5]
Při spuštění programu se zobrazí okénku Log in/Sing in. nezobrazuje se ikonka na liště.
![image](https://cloud.githubusercontent.com/assets/16975043/12704013/982dd2e8-c851-11e5-8f40-3c0038ea9168.png)

**Comment by TekuSP** [comment]
Opraveno a bude vydáno v dalším patchi.
